dataset:
  root: DB/LJspeech
  train_part: 0.95
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 8
  batch_size: 32
  clip_grad_norm: 10
  epochs: 42
  optimizer:
    lr: 0.001 # 0.0003 - Karpathy great constant
    # weight_decay: 0.001 - leave default

wandb:
  project: quartznet_ljspeech
  log_interval: 12
model:
  name: _quartznet5x5_config
  vocab_size: 120
  feat_in: 64
