dataset:
  root: DB/LJspeech
  train_part: 0.95
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 16
  batch_size: 16
  clip_grad_norm: 15
  epochs: 50
  optimizer:
    lr: 0.005
    weight_decay: 0.001

wandb:
  project: quartznet_ljspeech
  log_interval: 25
model:
  name: _quartznet5x5_config
  vocab_size: 120
  feat_in: 64
